//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentacarTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public int IDUsers { get; set; }
        public System.DateTime LogTime { get; set; }
        public int ActionID { get; set; }
        public string TableName { get; set; }
    
        public virtual Actions Actions { get; set; }
        public virtual Users Users { get; set; }
    }
}
