//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentacarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upkeep
    {
        public int IDUpkeep { get; set; }
        public int IDCars { get; set; }
        public System.DateTime BeginUpkeepDate { get; set; }
        public System.DateTime EndUpkeepDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
