//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentacarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IDUsers { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int IDRole { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
